"""
JWT Authentication and Authorization
Verifies JWT tokens generated by Better Auth

Security Implementation:
- Verifies JWT signature using shared BETTER_AUTH_SECRET
- Validates token expiration
- Extracts user_id from 'sub' claim
- Provides FastAPI dependency for protected routes
"""

import logging
import jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from app.config import get_settings


logger = logging.getLogger(__name__)
settings = get_settings()
security = HTTPBearer()


def get_current_user(
    credentials: HTTPAuthorizationCredentials = Depends(security)
) -> str:
    """
    Extract and verify JWT token, return user_id.

    This dependency function:
    1. Extracts token from Authorization: Bearer <token> header
    2. Verifies signature using BETTER_AUTH_SECRET
    3. Validates expiration (exp claim)
    4. Decodes payload to get user_id from 'sub' claim
    5. Returns authenticated user_id for use in endpoints

    Args:
        credentials: HTTP Bearer token from Authorization header

    Returns:
        str: User ID from token's 'sub' claim (e.g., "user-123")

    Raises:
        HTTPException: 401 Unauthorized if:
            - Token is missing
            - Signature is invalid
            - Token is expired
            - 'sub' claim is missing or empty

    Usage in Protected Endpoints:
        @router.get("/api/{user_id}/tasks")
        def get_tasks(
            user_id: str,
            auth_user_id: str = Depends(get_current_user)
        ):
            if user_id != auth_user_id:
                raise HTTPException(403, "Forbidden")
            # ... proceed with user-scoped operation
    """
    try:
        token = credentials.credentials

        # Decode and verify JWT
        payload = jwt.decode(
            token,
            settings.better_auth_secret,
            algorithms=[settings.jwt_algorithm]
        )

        # Extract user_id from 'sub' claim
        user_id = payload.get("sub")

        # Validate user_id is present and not empty
        if not user_id or not isinstance(user_id, str) or user_id.strip() == "":
            logger.warning("JWT token missing valid 'sub' claim")
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid token: missing subject"
            )

        logger.debug(f"Authenticated user: {user_id}")
        return user_id.strip()

    except jwt.ExpiredSignatureError:
        logger.info("JWT token expired")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Token expired"
        )
    except jwt.InvalidTokenError as e:
        logger.warning(f"Invalid JWT token: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token"
        )
    except HTTPException:
        # Re-raise HTTPException without wrapping
        raise
    except Exception as e:
        # Catch any unexpected errors
        logger.error(f"Unexpected error during JWT verification: {str(e)}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication failed"
        )
